ninject/Ninject

- src/Ninject/Activation/Caching/ActivationCache.cs
- src/Ninject/Activation/Pipeline.cs
- src/Ninject/Activation/Strategies/ActivationCacheStrategy.cs
- src/Ninject/Modules/CompiledModuleLoaderPlugin.cs
Hello, I'm working on a static analysis tool that looks for missing null checks.  It suggested you add these checks:
Reasons:
ActivationCache constructor: if cachePruner is null, the constructor will always throw an exception
Pipeline constructor: fs activationCache is null and subsequently Activate or Deactivate is called, it will throw an exception (because Activate and Deactive both dereference activationCache)
ActivationCacheStrategy constructor: if activationCache is null and subsequently Activate or Deactivate is called, it will throw an exception (because Activate and Deactive both dereference activationCache)
CompiledModuleLoaderPlugin constructor: if assemblyNameRetriever is null and subsequently LoadModules is called, it will throw an exception because LoadModules dereferences …
> add missing null checks to public constructors

- src/Ninject/Planning/Bindings/BindingConfigurationBuilder.cs
- src/Ninject/Syntax/IBindingWithSyntax.cs
I Added strongly typed overloads of WithConstructorArgument which use a callback to get the value so that you do not need to pass the type of the argument any more. This also guarantees that the callback you pass returns the type that you specified as a generic argument.
> Added strongly typed overloads of WithConstructorArgument which use callback to get the value

- src/Ninject.Test/Integration/CircularDependenciesTests.cs
- src/Ninject/Activation/Context.cs
- src/Ninject/Infrastructure/Multimap.cs
- src/Ninject/KernelConfiguration.cs
fixes issue reported in #143 
all tests pass plus those extra tests mentioned in #143.
> alternate method of checking for cyclical dependencies allows for open generics

- README.md
Just noticed this because I was doing a package upgrade and wanted to see what had changed.
> Fix broken release notes link, update link text

- src/Ninject/Properties/AssemblyInfo.cs
Ninject is no longer marked as CLS compliant where it once was. This PR reintroduces an assemblyinfo file with the CLSCompliant attribute marked true.
> Add assemblyinfo with CLSCompliant(true)

- src/Ninject.Test/Unit/Planning/PlanTests.cs
- src/Ninject/Planning/Plan.cs
* Improves performance and reduces allocations in Plan.
* Add unit tests for Plan.
**Before:**
|                    Method |      Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|-------------------------- |----------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
|  HasDirective_Match_First |  77.12 ns | 0.9070 ns | 0.8484 ns |      0.0228 |           - |           - |                96 B |
| HasDirective_Match_Middle | 169.68 ns | 1.1336 ns | 1.0603 ns |      0.0226 |           - |           - |                96 B |
|   HasDirective_Match_Last | 240.03 ns | 0.8890 ns | 0.7881 ns |      0.0224 |           - |           - |                96 B |
|      HasDirective_NoMatch | 256.20 ns | 1.8254 ns | …
> Improve performance and reduce allocations in Plan.

- src/Ninject.Benchmarks/Planning/PlanBenchmark.cs
- src/Ninject/Planning/Plan.cs
Improves performance and reduces allocations further for **Plan**.
**Before:**
|                    Method |       Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|-------------------------- |-----------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
|  HasDirective_Match_First |  39.620 ns | 0.2334 ns | 0.2069 ns |      0.0209 |           - |           - |                88 B |
| HasDirective_Match_Middle | 121.500 ns | 1.5366 ns | 1.3622 ns |      0.0207 |           - |           - |                88 B |
|   HasDirective_Match_Last | 189.981 ns | 0.7099 ns | 0.6640 ns |      0.0207 |           - |           - |                88 B |
|      HasDirective_NoMatch | 209.746 ns | 2.0663 ns | 1.9329 ns …
> Improve performance and reduce allocations further for Plan.

- src/Ninject.Test/Ninject.Test.csproj
- src/Ninject/Properties/AssemblyInfo.cs
Expose internals of **Ninject** to **Ninject.Test** to allows us to test internals.
Strongname **Ninject.Test**, and only optimize code in **Release** configuration (to allow us to debug tests).
> Expose internals of Ninject to Ninject.Test

- src/Ninject.Benchmarks/Injection/ExpressionInjectorFactoryBenchmark.cs
- src/Ninject.Benchmarks/Injection/ReflectionInjectorFactoryBenchmark.cs
- src/Ninject/Injection/ExpressionInjectorFactory.cs
Minor speedup for creation of constructor and method injector in **ExpressionInjectorFactory**, and reduce allocations.
Add benchmarks for **ExpressionInjectorFactory** and **ReflectionInjectorFactory**.
**Before:**
|                 Method |           Mean |         Error |        StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|----------------------- |---------------:|--------------:|--------------:|------------:|------------:|------------:|--------------------:|
| Create_ConstructorInfo | 128,727.325 ns | 1,968.6996 ns | 1,841.5228 ns |      1.2207 |      0.4883 |           - |              5616 B |
**After:**
|                 Method |           Mean |       Error |      StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op | …
> Minor speedup for creation of constructor and method injector

- src/Ninject.Benchmarks/Activation/PipelineBenchmark.cs
- src/Ninject/Activation/Pipeline.cs
Improves performance and reduce allocationss in **Pipeline** by avoiding virtual method calls and using `List<T>.ForEach(Action<T> action)` instead of `ExtensionsForIEnumerableOfT.Map(this IEnumerable<T> series, Action<T> action)` extension method.
**Before:**
|                                            Method |      Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|-------------------------------------------------- |----------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
|           Activate_WithStrategies_ObjectActivated |  34.86 ns | 0.0287 ns | 0.0240 ns |      0.0076 |           - |           - |                32 B |
|        Activate_WithStrategies_ObjectNotActivated | 107.14 ns | 0.0966 ns …
> Improve performance and reduce allocations in Pipeline

- src/Ninject.Benchmarks/Planning/PlannerBenchmark.cs
- src/Ninject.Test/Unit/Planning/PlannerTests.cs
- src/Ninject/Planning/Planner.cs
Improves performance and parallelism, and reduces allocations in **Planner** by:
* Eliminating virtual method calls.
* Using `List<T>.ForEach(Action<T> action)` instead of `ExtensionsForIEnumerableOfT.Map<T>(this IEnumerable<T> series, Action<T> action)`.
* Executing strategies outside of write lock.
* Removing duplicate null check in `Planner.CreateEmptyPlan(Type type)`.
** Before:**
|                            Method |        Mean |      Error |     StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|---------------------------------- |------------:|-----------:|-----------:|------------:|------------:|------------:|--------------------:|
|           GetPlan_Existing_Serial |    40.68 ns |  0.0496 ns |  0.0464 ns |           - |           - |           - | …
> Improve performance and parallelism, and reduce allocations in Planner

- src/Ninject/Selection/Heuristics/IInjectionHeuristic.cs
- src/Ninject/Selection/Heuristics/StandardInjectionHeuristic.cs
Eliminate runtime type checks by introducing the following overloads:
* `bool ShouldInject(PropertyInfo property)` 
* `bool ShouldInject(MethodInfo method)`
I also removed the `bool ShouldInject(MemberInfo member)` overload, as that one is no longer used.
Note that this is a breaking change (but I doubt it affects anyone).
> Introduce ShouldInject overloads in IInjectionHeuristic

- src/Ninject.Test/Unit/Activation/RequestTests.cs
- src/Ninject.Test/Unit/ReadOnlyKernelTests.cs
- src/Ninject.Test/Unit/ResolutionExtensionsTests.cs
- src/Ninject/Activation/Request.cs
- src/Ninject/ReadOnlyKernel.cs
- src/Ninject/Syntax/ResolutionExtensions.cs
* Moves null checks for service and parameters arguments to Request.
* Removes duplicate null checks.
* Add unit tests.
> Move and remove duplicate null checks

- src/Ninject.Test/Unit/Planning/Bindings/BindingMetadataTests.cs
- src/Ninject/Planning/Bindings/BindingMetadata.cs
* Removes extra lookup in `BindingMetadata.Get<T>(string key)` and `BindingMetadata.Get<T>(string key, T defaultValue)`
* Removes duplicate argument check in `BindingMetadata.Get<T>(string key)`.
* Document exceptions that are thrown.
* Adds unit tests.
> Remove extra lookup and argument check in BindingMetadata

- src/Ninject/Modules/NinjectModule.cs
* Introduce a **List\<IBinding>** backing field for **NinjectModule.Bindings**. This eliminates a few virtual method calls.
* Use `List<T>.ForEach(Action<T> action)` instead of `ExtensionsForIEnumerable.Map<T>(this IEnumerable<T> series, Action<T> action)`, and no longer use method group to reduce allocations.
> Minor performance and allocation improvement for NinjectModule.

- src/Ninject.Test/Unit/AssemblyNameRetrieverTests.cs
- src/Ninject/Modules/AssemblyNameRetriever.cs
- src/Ninject/Modules/IAssemblyNameRetriever.cs
Fixed https://github.com/ninject/Ninject/issues/295
The file names are actually file full paths: https://github.com/ninject/Ninject/blob/master/src/Ninject/Modules/ModuleLoader.cs#L80
And the **Assembly.LoadFile** will load the assmebly into a new (anonymous) load context. https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/assemblyloadcontext.md#assembly-load-apis-and-loadcontext
> Use Assembly.LoadFile instead of Assembly.LoadFrom

- src/Ninject/Planning/Bindings/Resolvers/OpenGenericBindingResolver.cs
Eliminates double binding lookup in **OpenGenericBindingResolver**.
> Eliminate double binding lookup in OpenGenericBindingResolver

- src/Ninject.Benchmarks/Activation/Strategies/MethodInjectionStrategyBenchmark.cs
- src/Ninject/Activation/Strategies/MethodInjectionStrategy.cs
Improves performane and reduce allocations for **MethodInjectionStrategy**.
**Before:**
|   Method |     Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
--------- |---------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
Activate | 44.73 ns | 0.8975 ns | 0.7956 ns |      0.0190 |           - |           - |                80 B |
**After:**
|   Method |     Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
--------- |---------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
Activate | 28.88 ns | 0.5758 ns | 0.5386 ns |      0.0114 |           - |           - |                48 B |
> Improve performane and reduce allocations for MethodInjectionStrategy

- src/Ninject.Benchmarks/Infrastructure/Language/ExtensionsForListBenchmark.cs
- src/Ninject.Test/Unit/Infrastructure/Language/ExtensionsForListTests.cs
- src/Ninject/Infrastructure/Language/ExtensionsForList.cs
* Adds fast Union and Concat extension methods for **IReadOnlyList\<T>**.
The methods will be used in future PRs.
**Concat benchmarks:**
| Method |   Version |      Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|---------------------------------------------------------- |----------:|----------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
|          Concat_IReadOnlyListAndIList_FirstAndSecondEmpty |      Linq | 231.51 ns | 1.7821 ns | 1.5798 ns |      0.0129 |           - |           - |                56 B |
|          Concat_IReadOnlyListAndIList_FirstAndSecondEmpty |        PR |  21.48 ns | 0.1301 ns | 0.1217 ns |           - |           - |           - |                   - |          
| …
> Add fast Union and Concat extension methods.

- src/Ninject.Benchmarks/Selection/Heuristics/StandardConstructorScorerBenchmark.cs
- src/Ninject/Selection/Heuristics/StandardConstructorScorer.cs
Changed `StandardConstructorScorer.GetTargetType((ITarget target)` to be a static method.
> Changed StandardConstructorScorer.GetTargetType((ITarget target) to static

- src/Ninject.Benchmarks/Infrastructure/ReferenceEqualityTypeComparerBenchmark.cs
- src/Ninject.Benchmarks/ReadOnlyKernelBenchmark.cs
- src/Ninject.Test/Unit/Infrastructure/Language/ExtensionsForDictionaryTests.cs
- src/Ninject/Components/ComponentContainer.cs
- src/Ninject/GlobalKernelRegistration.cs
- src/Ninject/Infrastructure/Language/ExtensionsForDictionary.cs
- src/Ninject/Infrastructure/Multimap.cs
- src/Ninject/Infrastructure/ReferenceEqualityTypeComparer.cs
- src/Ninject/KernelBase.cs
- src/Ninject/KernelConfiguration.cs
- src/Ninject/Planning/Planner.cs
- src/Ninject/ReadOnlyKernel.cs
Improves performance of dictionaries with a type-based key by using a reference equality comparer.
**Result:**
|                                      Method |       Mean |     Error |    StdDev |
|-------------------------------------------- |-----------:|----------:|----------:|
|    DictionaryLookup_Match_ReferenceEquality | 11.0069 ns | 0.0251 ns | 0.0235 ns |
|              DictionaryLookup_Match_Default | 13.0641 ns | 0.0165 ns | 0.0138 ns |
|  DictionaryLookup_NoMatch_ReferenceEquality | 13.4028 ns | 0.0572 ns | 0.0478 ns |
|            DictionaryLookup_NoMatch_Default | 12.9323 ns | 0.0274 ns | 0.0229 ns |
|               GetHashCode_ReferenceEquality |  1.4412 ns | 0.0023 ns | 0.0021 ns |
|                         GetHashCode_Default |  3.5885 ns | 0.0029 ns | 0.0026 ns |
| …
> Use reference equality comparer for Type-based keys

- src/Ninject.Benchmarks/Activation/Caching/CacheBenchmark.cs
- src/Ninject.Test/Unit/Activation/Caching/CacheTests.cs
- src/Ninject.Test/Unit/Activation/ContextTests.cs
- src/Ninject/Activation/Caching/Cache.cs
- src/Ninject/Activation/Caching/ICache.cs
- src/Ninject/Activation/Context.cs
> Marked **WIP** as I still need to update tests for **Context**, and want to increase test coverage for **Cache**.
**Cache:**
* Add overloads of **Remember** and **TryGet** that take scope.
* Fixed thread safety.
* Improve overal performance and reduce allocations.
**Context:**
* Use new `Remember(IContext context, object scope, InstanceReference reference)` and `TryGet(IContext context, object scope)` overloads on **Cache**.
* Only try to get instance from cache when there's a scope
**Before:**
|                                         Method |       Mean |     Error |     StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|----------------------------------------------- |-----------:|----------:|-----------:|------------:|------------:|------------:|--------------- …
> Improve performance and reduce allocations of Cache

- src/Ninject.Test/Unit/Selection/SelectorTests.cs
Fix test to not rely on order by which System.Reflection returns properties.
> Fix test to not rely on System.Reflection order

- CHANGELOG.md
- src/Ninject.Benchmarks/ReadOnlyKernelBenchmark.cs
- src/Ninject.Test/Unit/Activation/Providers/StandardProviderTests.cs
- src/Ninject.Test/Unit/ReadOnlyKernelTests.cs
- src/Ninject.Test/Unit/ResolutionExtensionsTests.cs
- src/Ninject/Activation/Blocks/ActivationBlock.cs
- src/Ninject/IReadOnlyKernel.cs
- src/Ninject/KernelBase.cs
- src/Ninject/Planning/Targets/Target.cs
- src/Ninject/ReadOnlyKernel.cs
- src/Ninject/Syntax/IResolutionRoot.cs
- src/Ninject/Syntax/ResolutionExtensions.cs
Added an `object ResolveSingle(IRequest request)` method to **IResolutionRoot** which is optimized for resolving a single instance of a given service.
This new method is used in the **Get**, **TryGet** and **TryGetAndThrowOnInvalidBinding** extension methods.
Result of the [IocPerformance](https://github.com/danielpalme/IocPerformance) benchmark with activation cache disabled:
**PR:**
Test | Singlethreaded | Multithreaded
-----|----------------:|--------------:
Singleton |       392    |    446
Transient  |      883     |   568
Combined   |     2683     |  1921
Complex    |     8378     |  5949
**master:**
Test | Singlethreaded | Multithreaded
-----|----------------:|--------------:
Singleton  |      574     |   590
Transient  |     1069    |    716
Combined    |    3347    |   2011 …
> Improve performance for resolving a single instance

- src/Ninject.Test/Integration/ConstantTests.cs
- src/Ninject.Test/Integration/ReadOnlyKernelTests.cs
- src/Ninject/ReadOnlyKernel.cs
Resolve using standard binding resolver before resolving as a collection.
Fixes #333.
> Resolve using standard binding resolver before resolving as a collection

- src/Ninject.Test/Integration/ReadOnlyKernelTests.cs
- src/Ninject/ReadOnlyKernel.cs
Do not attempt to handle unbound generic type definition as collection.
Fixes #340.
> Do not attempt to handle unbound generic type definition as collection.

- src/Ninject.Test/Integration/ReadOnlyKernelTests.cs
- src/Ninject/ReadOnlyKernel.cs
Avoid stackoverflow when handling missing bindings, and none of the bindings match.
Fixes #341.
> Avoid stackoverflow when handling missing bindings, and no bindings match

- src/Ninject.Test/Integration/StandardKernelTests.cs
- src/Ninject/INinjectSettings.cs
- src/Ninject/NinjectSettings.cs
- src/Ninject/ReadOnlyKernel.cs
The problem is described in https://github.com/ninject/Ninject/issues/376 and the solution is straight forward. I have added two test cases for the `StandardKernel` to ensure that the `IServiceProvider` implementation is compliant with the behavior defined in the documentation.
> Fixing IServiceProvider.GetService implementation (fixes #376)

- src/Ninject.Test/Integration/ReadOnlyKernelTests.cs
- src/Ninject/Syntax/ResolutionExtensions.cs
This should fix #378.
All of the generic `TryGet<T>` overloads and _one_ of the three `TryGet` overloads already set `isUnique` to `true`. The other two are the outliers that behave in a way that is inconsistent with the documented/expected behavior of the method.
> Consolidated handling of isUnique parameter for TryGet (fixes #378)
